//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Tasks = new HashSet<Task>();
            this.Reminders = new HashSet<Reminder>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
    }
}
