//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSRM_liveEntities : DbContext
    {
        public CSRM_liveEntities()
            : base("name=CSRM_liveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<EmailStatus> EmailStatuses { get; set; }
        public DbSet<JobStatus> JobStatuses { get; set; }
        public DbSet<Log_T> Log_T { get; set; }
        public DbSet<NotificationLog> NotificationLogs { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Reminder> Reminders { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<UserPreference> UserPreferences { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ScheduledJob> ScheduledJobs { get; set; }
    }
}
