//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_T
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string ProcessType { get; set; }
        public string ProcessTypeCategory { get; set; }
        public System.DateTime AccessTime { get; set; }
        public string IPAddress { get; set; }
        public string DeviceInfo { get; set; }
    
        public virtual User User { get; set; }
    }
}
