//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationLogs = new HashSet<NotificationLog>();
        }
    
        public int NotificationID { get; set; }
        public int TaskID { get; set; }
        public int UserID { get; set; }
        public string Channel { get; set; }
        public string Message { get; set; }
        public System.DateTime ScheduledTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<NotificationLog> NotificationLogs { get; set; }
        public virtual Task Task { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual Task Task2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
