//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public System.DateTime ReminderDateTime { get; set; }
        public string NotificationMethod { get; set; }
        public string ReminderMessage { get; set; }
        public string ReminderStatusDesc { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string WaitType { get; set; }
        public int WaitPeriod { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
