//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ScheduleDescription { get; set; }
        public bool IsReccurringjob { get; set; }
        public string RecurrencePattern { get; set; }
        public string WaitType { get; set; }
        public Nullable<int> WaitPeriod { get; set; }
        public bool IsRecurring { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> JobStatusID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int ExecutionCount { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public int FailedAttempts { get; set; }
    
        public virtual JobStatus JobStatus { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
