//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledJob
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ScheduledSql { get; set; }
        public System.DateTime FirstRunOn { get; set; }
        public System.DateTime LastRunOn { get; set; }
        public Nullable<int> WaitPeriod { get; set; }
        public string WaitType { get; set; }
        public int IsRepeatable { get; set; }
        public int IsEnabled { get; set; }
    }
}
