//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.Notifications2 = new HashSet<Notification>();
            this.Reminders = new HashSet<Reminder>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int TaskID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsRecurring { get; set; }
        public string RecurrencePattern { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string TaskStatus { get; set; }
        public string Attachments { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string PriorityDescription { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual ICollection<Notification> Notifications2 { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual User User { get; set; }
    }
}
