//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
            this.Log_T = new HashSet<Log_T>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.Notifications2 = new HashSet<Notification>();
            this.Reminders = new HashSet<Reminder>();
            this.Schedules = new HashSet<Schedule>();
            this.Tasks = new HashSet<Task>();
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public bool IsAdmin { get; set; }
        public bool NotificationsEnabled { get; set; }
        public string AvatarUrl { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Log_T> Log_T { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual ICollection<Notification> Notifications2 { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
